### ISSUE TITLE
How do you install Prodigy to be used by this project

### ISSUE THREAD

**Issue by filippo82** [koaning/arxiv-frontpage#3]
Hi Vincent,

first of all let me say that this is a beautiful and inspirational project 😇

As the readme clearly states, this project assumes that Prodigy is available. However, looking at the code and the workflows, I don't see where/how Prodigy is either installed and/or made available to the Python modules.

To be clear, I know that Prodigy requires a license to be able to download it.

**Comment by koaning** [comment]
It's more that the data that comes out of prodigy is in a specific format. Prodigy is installed with a separate command because you [need the license key in the install command](https://prodi.gy/docs/install#pip).

You can see [here](https://github.com/koaning/arxiv-frontpage/blob/main/frontpage/datastream.py#L30) that the project connects to a Prodigy database. 

I may remove the hard link to Prodigy, but I'm a bit swamped with many hobbys now which is why this isn't prioritised.
